export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";
export const USER_FOLLOWERS = "USER_FOLLOWERS";
export const USER_FOLLOWING = "USER_FOLLOWING";
export const USER_REPOSITORIES = "USER_REPOSITORIES";